# Generated by Django 5.0.14 on 2026-08-29 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20)),
                ('external_account_ref', models.CharField(blank=True, max_length=255)),
                ('token_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider_key'], name='integration_user_id_d4f0c4_idx')],
            },
        ),
    ]
