# Generated by Django 5.0.14 on 2026-08-29 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_class', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Deposit'), ('gold', 'Gold'), ('silver', 'Silver'), ('crypto', 'Crypto'), ('stock', 'Stocks'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=8, default=1, max_digits=24)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_mock', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('asset_class', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Deposit'), ('gold', 'Gold'), ('silver', 'Silver'), ('crypto', 'Crypto'), ('stock', 'Stocks'), ('other', 'Other')], max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=120)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='IRT', max_length=8)),
                ('is_mock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_allocation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_recurring', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liability_type', models.CharField(choices=[('loan', 'Loan'), ('credit_card', 'Credit Card'), ('bnpl', 'BNPL / Installment'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_mock', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.liability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Portfolio', max_length=120)),
                ('is_mock', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_class', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Deposit'), ('gold', 'Gold'), ('silver', 'Silver'), ('crypto', 'Crypto'), ('stock', 'Stocks'), ('other', 'Other')], max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.portfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('investment_horizon', models.CharField(choices=[('short', 'Short-term'), ('medium', 'Medium-term'), ('long', 'Long-term')], default='medium', max_length=10)),
                ('liquidity_preference', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('max_crypto_allocation_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('max_single_asset_concentration_pct', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('emergency_reserve_months', models.PositiveSmallIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], max_length=10)),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('food', 'Food'), ('shopping', 'Shopping'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('bills', 'Bills'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('is_mock', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'asset_class'], name='finance_fin_user_id_953466_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'received_at'], name='finance_inc_user_id_3efa41_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='one_risk_profile_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'occurred_at'], name='finance_tra_user_id_477e81_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'occurred_at'], name='finance_tra_user_id_5ef90c_idx'),
        ),
    ]
