"""
Deterministic Financial Engine.

Every number shown on the dashboard is computed here from database
records -- never guessed, estimated, or generated by an LLM. Any
future AI Financial Agent must call into this module as a *tool*
(see apps.ai) and treat its output as ground truth, not the other
way around.

All functions take a `user` and return plain Decimal/dict values so
they are trivially unit-testable without HTTP or template concerns.
"""

from dataclasses import dataclass, field
from datetime import timedelta
from decimal import Decimal

from django.db.models import Sum
from django.utils import timezone

from .models import (
    Asset,
    AssetClass,
    FinancialAccount,
    Goal,
    Income,
    Liability,
    RiskProfile,
    Transaction,
    TransactionType,
)

ZERO = Decimal("0")


def _sum(queryset, field_name="amount"):
    return queryset.aggregate(total=Sum(field_name))["total"] or ZERO


@dataclass
class AllocationSlice:
    asset_class: str
    value: Decimal
    pct: Decimal


@dataclass
class FinancialSummary:
    total_cash: Decimal = ZERO
    total_investments: Decimal = ZERO
    total_gold: Decimal = ZERO
    total_silver: Decimal = ZERO
    total_crypto: Decimal = ZERO
    total_stocks: Decimal = ZERO
    total_other_assets: Decimal = ZERO
    total_assets: Decimal = ZERO
    total_debt: Decimal = ZERO
    net_worth: Decimal = ZERO
    monthly_income: Decimal = ZERO
    monthly_expenses: Decimal = ZERO
    monthly_savings: Decimal = ZERO
    savings_rate_pct: Decimal = ZERO
    allocation: list = field(default_factory=list)


def get_total_cash(user) -> Decimal:
    return _sum(
        FinancialAccount.objects.filter(
            user=user, is_active=True, asset_class__in=[AssetClass.CASH, AssetClass.BANK]
        ),
        "current_balance",
    )


def get_asset_totals(user) -> dict:
    """Returns total value per AssetClass across both FinancialAccount balances and standalone Asset records."""
    totals = {choice: ZERO for choice in AssetClass.values}

    for acc in FinancialAccount.objects.filter(user=user, is_active=True):
        totals[acc.asset_class] += acc.current_balance

    for asset in Asset.objects.filter(user=user):
        totals[asset.asset_class] += asset.total_value

    return totals


def get_total_debt(user) -> Decimal:
    return _sum(Liability.objects.filter(user=user), "outstanding_balance")


def get_monthly_income(user, as_of=None) -> Decimal:
    as_of = as_of or timezone.now()
    window_start = as_of - timedelta(days=30)
    return _sum(Income.objects.filter(user=user, received_at__gte=window_start, received_at__lte=as_of))


def get_monthly_expenses(user, as_of=None) -> Decimal:
    as_of = as_of or timezone.now()
    window_start = as_of - timedelta(days=30)
    return _sum(
        Transaction.objects.filter(
            user=user,
            transaction_type=TransactionType.EXPENSE,
            occurred_at__gte=window_start,
            occurred_at__lte=as_of,
        )
    )


def get_expense_breakdown(user, as_of=None) -> dict:
    as_of = as_of or timezone.now()
    window_start = as_of - timedelta(days=30)
    qs = (
        Transaction.objects.filter(
            user=user,
            transaction_type=TransactionType.EXPENSE,
            occurred_at__gte=window_start,
            occurred_at__lte=as_of,
        )
        .values("category")
        .annotate(total=Sum("amount"))
        .order_by("-total")
    )
    return {row["category"]: row["total"] for row in qs}


def build_financial_summary(user, as_of=None) -> FinancialSummary:
    """
    The single source of truth for dashboard numbers.
    Net Worth = Total Assets - Total Liabilities. No shortcuts.
    """
    as_of = as_of or timezone.now()

    asset_totals = get_asset_totals(user)
    total_cash = asset_totals[AssetClass.CASH] + asset_totals[AssetClass.BANK]
    total_gold = asset_totals[AssetClass.GOLD]
    total_silver = asset_totals[AssetClass.SILVER]
    total_crypto = asset_totals[AssetClass.CRYPTO]
    total_stocks = asset_totals[AssetClass.STOCK]
    total_other = asset_totals[AssetClass.OTHER]

    total_investments = total_gold + total_silver + total_crypto + total_stocks
    total_assets = total_cash + total_investments + total_other
    total_debt = get_total_debt(user)
    net_worth = total_assets - total_debt

    monthly_income = get_monthly_income(user, as_of)
    monthly_expenses = get_monthly_expenses(user, as_of)
    monthly_savings = monthly_income - monthly_expenses
    savings_rate_pct = (
        (monthly_savings / monthly_income * Decimal("100")) if monthly_income > ZERO else ZERO
    )

    allocation = []
    if total_assets > ZERO:
        for asset_class, value in [
            (AssetClass.CASH, total_cash),
            (AssetClass.GOLD, total_gold),
            (AssetClass.SILVER, total_silver),
            (AssetClass.CRYPTO, total_crypto),
            (AssetClass.STOCK, total_stocks),
            (AssetClass.OTHER, total_other),
        ]:
            if value > ZERO:
                pct = (value / total_assets * Decimal("100")).quantize(Decimal("0.01"))
                allocation.append(AllocationSlice(asset_class=asset_class, value=value, pct=pct))

    return FinancialSummary(
        total_cash=total_cash,
        total_investments=total_investments,
        total_gold=total_gold,
        total_silver=total_silver,
        total_crypto=total_crypto,
        total_stocks=total_stocks,
        total_other_assets=total_other,
        total_assets=total_assets,
        total_debt=total_debt,
        net_worth=net_worth,
        monthly_income=monthly_income,
        monthly_expenses=monthly_expenses,
        monthly_savings=monthly_savings,
        savings_rate_pct=savings_rate_pct.quantize(Decimal("0.1")),
        allocation=allocation,
    )


def calculate_investable_capital(user, as_of=None) -> Decimal:
    """
    Deliberately NOT "everything not spent = investable".

    Investable Capital =
        Total Cash
        - Emergency Reserve (RiskProfile.emergency_reserve_months * avg monthly expenses)
        - Near-term Goal Requirements (goals due within 90 days)
        - Outstanding near-term debt obligations
    Floored at zero.
    """
    as_of = as_of or timezone.now()
    total_cash = get_total_cash(user)
    monthly_expenses = get_monthly_expenses(user, as_of) or ZERO

    risk_profile = RiskProfile.objects.filter(user=user).first()
    reserve_months = risk_profile.emergency_reserve_months if risk_profile else 3
    emergency_reserve = monthly_expenses * Decimal(reserve_months)

    near_term_cutoff = (as_of + timedelta(days=90)).date()
    near_term_goal_gap = _sum(
        Goal.objects.filter(user=user, is_achieved=False, deadline__lte=near_term_cutoff),
        "target_amount",
    ) - _sum(
        Goal.objects.filter(user=user, is_achieved=False, deadline__lte=near_term_cutoff),
        "current_allocation",
    )
    near_term_goal_gap = max(near_term_goal_gap, ZERO)

    debt_obligations = get_total_debt(user)

    investable = total_cash - emergency_reserve - near_term_goal_gap - debt_obligations
    return max(investable, ZERO)


def calculate_goal_funding_gap(user, goal: Goal) -> Decimal:
    return max(goal.target_amount - goal.current_allocation, ZERO)
